### ISSUE TITLE
Référence API non diponible sur Github

### ISSUE THREAD

**Issue by SofiyanIfren** [MTES-MCT/trackdechets#1336]
Bonjour,

J'ai repéré une erreur dans la documentation que je voulais remonter, et par là-même m'en assurer. Cette erreur de typage se trouve dans la donc (Référence > Référence API > Déchets dangereux) mais je ne trouve la ref. API nulle part sur Github.

Pour info, l'erreur est pour l'InputObject AppendixFormInput : le readableId n'est pas de type ID! mais String!

Merci

**Comment by elishowk** [comment]
bonjour, Vous parlez bien d'une erreur dans cette section de la doc ? https://developers.trackdechets.beta.gouv.fr/reference/api-reference/bsdd/inputObjects#appendixforminput

**Comment by SofiyanIfren** [comment]
@elishowk oui, en effet

**Comment by elishowk** [comment]
Pourtant, dans la documentation comme dans le code source, readableId est bien de type ID:
voir ici : `back/src/forms/typeDefs/bsdd.inputs.graphql`

```
"Payload de création d'une annexe 2"
input AppendixFormInput {
  "Identifiant unique du bordereau"
  id: ID!

  """
  N° de bordereau

  Déprécié : L'id du bordereau doit être utilisé comme identifiant (paramètre id).
  Le readableId permet de le récupérer via la query form.
  """
  readableId: ID
}
```

Ou bien on s'est mal compris ?

**Comment by SofiyanIfren** [comment]
Le readableId est de type String!

**Comment by elishowk** [comment]
Effectivement mais le champ de l'input en question est déprécié et on ne va pas faire de modification dessus pour ne pas créer de breaking changes sur l'api. Le `readableId` est un `String` partout ailleurs toutefois.

Merci d'avoir fait remonté le problème.
