### ISSUE TITLE
Possibilité de signer les BSD avec un mauvais code de sécurité

### ISSUE THREAD

**Issue by papXav** [MTES-MCT/trackdechets#1980]
Bonjour,

Il est possible de signé un bsd en indiquant un mauvais code de sécurité (ayant même plus de 4 caractère) comme dans la capture suivante. C'est aussi le cas via l'api.
![image](https://user-images.githubusercontent.com/100789382/207872817-d45cb70d-133f-4cbe-a697-ccbdb55f2152.png)

Merci

**Comment by providenz** [comment]
Bonjour et merci pour votre retour, une réponse vous a été apportée sur le forum.
