### ISSUE TITLE
Presser la touche entrée sur choix déroulant créé un retour à la page précédente

### ISSUE THREAD

**Issue by Cdk29** [MTES-MCT/trackdechets#823]
Bonjour,

Lorsque j'appuie sur la touche entrée dans une case où une recherche d'entreprise est effectuée et où je dois sélectionner une entreprise, appuyer sur la touche entrée si aucun choix n'est valide ou a été fait provoque un retour à la page/étape précédente.

Par exemple : **_Création d'un BSD >> Installation de destination >> Numéro de SIRET ou nom de l'entreprise_**, si je tape machinalement "EVTV" qui ne retourne pas de résultat et que j'appuie sur entrée, je retourne à l'étape précédente.

Peut être est-ce le comportement voulu mais je le trouve assez déroutant. 

Test fait sur Windows 10, Chrome.

**Comment by Zhouzi** [comment]
Bonjour,

Désolé pour le retard, nous recevons de nombreuses demandes de support via différents canaux. Nous sommes plus réactifs sur le forum technique : https://forum.trackdechets.beta.gouv.fr/

Merci pour le signalement, ce n'est effectivement pas le comportement voulu. J'ai créé un ticket dans notre backlog pour le traiter 👍

**Comment by Zhouzi** [comment]
On a bien un ticket pour corriger ce bug dans notre backlog, je clos cette issue qui fait doublon et qu'on risque d'oublier de mettre à jour. La meilleure façon d'être tenu au courant des évolutions techniques est de [s'inscrire à la newsletter technique](https://0806de2d.sibforms.com/serve/MUIEAHQwLI4DmWML854ZRqMf-Ifiaw4ag7SHXC0IEIbQIZ1IcPFLnmOXxyJ4laAju06C0tkavZ3ys2dtB5U1uJjb1grzODmz6h28p7hkypvWShtiCFLOAu6t4OwEC_rZLaCil0SMHjs7xo3Sg5kfo4VLt6TNwZdYh6qkeM8u6D6h_jp_5G_ASr7fnyZUtM_W4nTy51no65EcNRqj). On envoi une nouvelle édition à chaque release pour partager le change log ainsi que les chantiers à venir.
